version: "3.7"
services:
  tessera1:
    image: lacnetnetworks/lacchain-tessera:21.1.1
    container_name: writer-tessera-local-01
    environment:
      PUBLIC_IP: writer-tessera-local-01
      DNS_NAME:  lacchain.com
      HOST_TESSERA_PEER: "writer-tessera-local-02"
      verbosity: INFO
    volumes:
      - ./files/tesserakey1:/opt/lacchain/tessera/keystore
    networks:
      lacchain:
        ipv4_address: 172.16.238.14
    ports:
      - 4040:4040
      - 4444:4444
  besu1: 
    image: lacnetnetworks/lacchain-besu:21.7.4
    container_name: writer-besu-local-01
    environment:
      BESU_LOGGING: INFO
      BESU_P2P_PORT: 60606
      BESU_RPC_HTTP_PORT    : 4545
      BESU_RPC_WS_PORT      : 4546
      BESU_PRIVACY_URL      : http://writer-tessera-local-01:4444
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        /opt/besu/bin/besu --genesis-file=/etc/genesis/genesis.json --data-path=/data/besu public-key  export-address --to=/data/besu/nodeAddress
        sleep 3; 
        /opt/besu/bin/besu  --config-file=/etc/besu/config.toml  --node-private-key-file=/data/besu/key  --privacy-marker-transaction-signing-key-file=/data/besu/key
    ports:
     # - 4545:4545
      - 5546:4546
      - 60606:60606
    volumes:
      - ./tessera1/data:/data/besu
      - ./files/genesis.json:/etc/genesis/genesis.json
      - ./files/config-writer-tessera.toml:/etc/besu/config.toml
      - ./files/nodekey1:/data/besu/key
      - ./files/tesserakey1:/tessera/keystore
    networks:
      lacchain:
        ipv4_address: 172.16.238.10
  relay1:
    image: lacnetnetworks/relay-signer-lacchain:1.0.0
    container_name: relay-signer-local-01
    environment:
      HOST_BESU: writer-besu-local-01
      CONTRACT_ADDRESS: '0x1Fa12c57ABab623beCc34A69cB526AD39c6338D6'
    depends_on:
      besu1:
        condition: service_started
    ports:
      - 9001
    volumes:
      - ./files/nodekey1:/opt/secret/key
    networks:
      lacchain:
        ipv4_address: 172.16.238.11
  nginx1:
    image: lacnetnetworks/writer-nginx-lacchain:1.0.0
    container_name: writer-nginx-local-01
    environment:
      HOST_RELAY_SIGNER: relay-signer-local-01
      HOST_BESU: writer-besu-local-01
    depends_on:
      besu1:
        condition: service_started
    ports:
      - 4545:80
    volumes:
      - ./tessera1/data:/opt/secret
    networks:
      lacchain:
        ipv4_address: 172.16.238.12
  tessera2:
    image: lacnetnetworks/lacchain-tessera:21.1.1
    container_name: writer-tessera-local-02
    environment:
      PUBLIC_IP: writer-tessera-local-02
      DNS_NAME:  lacchain.com
      HOST_TESSERA_PEER: "writer-tessera-local-01"
      verbosity: INFO
    volumes:
      - ./files/tesserakey2:/opt/lacchain/tessera/keystore
    networks:
      lacchain:
         ipv4_address: 172.16.238.24
  besu2: 
    image: lacnetnetworks/lacchain-besu:21.7.4
    container_name: writer-besu-local-02
    environment:
      BESU_LOGGING: INFO
      BESU_P2P_PORT: 60606
      BESU_RPC_HTTP_PORT    : 4545
      BESU_RPC_WS_PORT      : 4546
      BESU_PRIVACY_URL      : http://writer-tessera-local-02:4444
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        /opt/besu/bin/besu --genesis-file=/etc/genesis/genesis.json --data-path=/data/besu public-key  export-address --to=/data/besu/nodeAddress
        sleep 3; 
        /opt/besu/bin/besu  --config-file=/etc/besu/config.toml  --node-private-key-file=/data/besu/key  --privacy-marker-transaction-signing-key-file=/data/besu/key   --bootnodes=enode://21df19d8363b5ddc6ce544696c70d635403555bd9559fc01f36dd8d0f84a49042420d61296fb771c8e79f17f788b7144f51fef4485621242d892ab1e3f47c420@172.16.238.10:60606
    ports:
      #- 4546:4545
      - 5547:4546
      - 60607:60607
    volumes:
      - ./tessera2/data:/data/besu
      - ./files/genesis.json:/etc/genesis/genesis.json
      - ./files/config-writer-tessera.toml:/etc/besu/config.toml
      - ./files/nodekey2:/data/besu/key
      - ./files/tesserakey2:/tessera/keystore
    networks:
      lacchain:
        ipv4_address: 172.16.238.20
  relay2:
    image: lacnetnetworks/relay-signer-lacchain:1.0.0
    container_name: relay-signer-local-02
    environment:
      HOST_BESU: writer-besu-local-02
      CONTRACT_ADDRESS: '0x1Fa12c57ABab623beCc34A69cB526AD39c6338D6'
    depends_on:
      besu2:
        condition: service_started
    ports:
      - 9001
    volumes:
      - ./files/nodekey2:/opt/secret/key
    networks:
      lacchain:
        ipv4_address: 172.16.238.21
  nginx2:
    image: lacnetnetworks/writer-nginx-lacchain:1.0.0
    container_name: writer-nginx-local-02
    environment:
      HOST_RELAY_SIGNER: relay-signer-local-02
      HOST_BESU: writer-besu-local-02
    depends_on:
      besu2:
        condition: service_started
    ports:
      - 4546:80
    volumes:
      - ./tessera2/data:/opt/secret
    networks:
      lacchain:
        ipv4_address: 172.16.238.22
  tessera3:
    image: lacnetnetworks/lacchain-tessera:21.1.1
    container_name: writer-tessera-local-03
    environment:
      PUBLIC_IP: writer-tessera-local-03
      DNS_NAME:  lacchain.com
      HOST_TESSERA_PEER: "writer-tessera-local-01"
      verbosity: INFO
    volumes:
      - ./files/tesserakey3:/opt/lacchain/tessera/keystore
    networks:
      lacchain:
         ipv4_address: 172.16.238.34
  besu3: 
    image: lacnetnetworks/lacchain-besu:21.7.4
    container_name: writer-besu-local-03
    environment:
      BESU_LOGGING: INFO
      BESU_P2P_PORT: 60606
      BESU_RPC_HTTP_PORT    : 4545
      BESU_RPC_WS_PORT      : 4546
      BESU_PRIVACY_URL      : http://writer-tessera-local-03:4444
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        /opt/besu/bin/besu --genesis-file=/etc/genesis/genesis.json --data-path=/data/besu public-key  export-address --to=/data/besu/nodeAddress
        sleep 3; 
        /opt/besu/bin/besu  --config-file=/etc/besu/config.toml  --node-private-key-file=/data/besu/key --privacy-marker-transaction-signing-key-file=/data/besu/key  --bootnodes=enode://21df19d8363b5ddc6ce544696c70d635403555bd9559fc01f36dd8d0f84a49042420d61296fb771c8e79f17f788b7144f51fef4485621242d892ab1e3f47c420@172.16.238.10:60606
    ports:
      #- 4547:4545
      - 5548:4546
      - 60608:60608
    volumes:
      - ./tessera3/data:/data/besu
      - ./files/genesis.json:/etc/genesis/genesis.json
      - ./files/config-writer-tessera.toml:/etc/besu/config.toml
      - ./files/nodekey3:/data/besu/key
      - ./files/tesserakey3:/tessera/keystore
    networks:
      lacchain:
        ipv4_address: 172.16.238.30
  relay3:
    image: lacnetnetworks/relay-signer-lacchain:1.0.0
    container_name: relay-signer-local-03
    environment:
      HOST_BESU: writer-besu-local-03
      CONTRACT_ADDRESS: '0x1Fa12c57ABab623beCc34A69cB526AD39c6338D6'
    depends_on:
      besu3:
        condition: service_started
    ports:
      - 9001
    volumes:
      - ./files/nodekey3:/opt/secret/key
    networks:
      lacchain:
        ipv4_address: 172.16.238.31
  nginx3:
    image: lacnetnetworks/writer-nginx-lacchain:1.0.0
    container_name: writer-nginx-local-03
    environment:
      HOST_RELAY_SIGNER: relay-signer-local-03
      HOST_BESU: writer-besu-local-03
    depends_on:
      besu3:
        condition: service_started
    ports:
      - 4547:80
    volumes:
      - ./tessera3/data:/opt/secret
    networks:
      lacchain:
        ipv4_address: 172.16.238.32
networks:
  lacchain:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"