# Every possible CLI should be in this file.
#
# Please use a plausible value, besu has to at least be able to parse it.
# If it is a multi-valued CLI make it a TOML array.
# If it is a number or boolean make it a number or boolean
# All other config options are strings, and must be quoted.

# Node Information
data-path="/data/besu"
genesis-file="/etc/genesis/genesis.json"
logging="INFO"
#node-private-key-file="/keys/nodekey"
min-gas-price=0

# Transaction Pool
tx-pool-retention-hours=999
tx-pool-max-size=1024

# P2P network
p2p-enabled=true
discovery-enabled=true
#p2p-host="35.226.244.229"
p2p-port=60606
max-peers=25
host-whitelist=["*"]


# JSON-RPC
rpc-http-enabled=true
rpc-http-cors-origins=["all"]
rpc-http-host="0.0.0.0"
rpc-http-port=4545
rpc-http-api=["ETH","NET","IBFT","WEB3","EEA","PRIV"]

rpc-http-authentication-enabled=false
revert-reason-enabled=true

bootnodes=["enode://a677d655440fc338eefb5e31c3db1e07b56afbc28dee74822f600b1fb81f3657343f04cb2f68e5dd44ea606e041642bacc9151d91ab0527c878db0005ea30ca0@34.73.175.75:60606","enode://aef21d8ba679f55a7c28bbafb826b84cf1db929916b4d322b590037a584a0d08aef9d836289b15c2c4ce7fdb9f2f4abf705314b85fba62a8f01539e92491da80@34.73.74.151:60606","enode://4791c69f6a11486ecc6d4450aa8922865f078816176e166ccfc1882ae06272bcf71bdf7fa1d99f1a8815a7899dae0119ea06bac59a4810f92c2a9c89689610ca@35.237.20.121:60606"]

# GRAPHQL-RPC
graphql-http-enabled=true
graphql-http-cors-origins=["all"]
graphql-http-host="0.0.0.0"
graphql-http-port=4547



# WebSockets API
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=4546
rpc-ws-api=["ETH","NET","IBFT","WEB3","EEA","PRIV"]
rpc-ws-authentication-enabled=false


# Permissioning
    # Permissioning end

# Privacy
privacy-enabled=true
#privacy-url="http://localhost:4444"
privacy-public-key-file="/tessera/keystore/nodeKey.pub"

#privacy-onchain-groups-enabled=false


# Metrics Push
    ##end metrics Push
network-id="648530"